mechanicat_bot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls'))
]

pages/urls.py
from django.urls import path
from pages import views

app_name = "pages"

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('dashboard/', views.DashboardView.as_view(), name="dashboard")
]

pages/models.py
from django.db import models

# Create your models here.

pages/views.py
from django.contrib.auth.views import LoginView as AuthLoginView, LogoutView as AuthLogoutView
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib import messages


class HomeView(TemplateView):
    template_name = 'pages/home.html'


class LoginView(AuthLoginView):
    template_name = 'pages/auth_form.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        messages.success(self.request, "Login successfully")
        return super(LoginView, self).get_success_url()

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data()
        context['action'] = 'Login'
        return context


class LogoutView(AuthLogoutView):
    next_page = reverse_lazy('pages:home')

    def dispatch(self, request, *args, **kwargs):
        messages.success(self.request, "Logout successfully")
        return super(LogoutView, self).dispatch(request, *args, **kwargs)


class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = 'pages/auth_form.html'
    success_url = reverse_lazy('pages:login')

    def get_context_data(self, **kwargs):
        context = super(SignUpView, self).get_context_data()
        context['action'] = 'Signup'
        return context

    def get_success_url(self):
        messages.success(self.request, "Your account has been created.")
        return super(SignUpView, self).get_success_url()


class DashboardView(TemplateView):
    template_name = 'pages/dashboard.html'

templates/base/general/alerts.html
{% if messages %}
    <div class="container">
        <div class="row">
            <div class="col">
                {% for message in messages %}
                    <div class="{{ message.tags }} alert alert-dismissible fade show">
                        <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                            <i class="fas fa-times"></i>
                        </button>
                        {% if message.level == 10 or message.level == 20 %}
                            <i class="fas fa-info"></i>
                        {% endif %}
                        {% if message.level == 25 %}
                            <i class="fas fa-check"></i>
                        {% endif %}
                        {% if message.level == 30 %}
                            <i class="fas fa-warning"></i>
                        {% endif %}
                        {% if message.level == 40 %}
                            <i class="fas fa-exclamation-circle"></i>
                        {% endif %}
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}

templates/base/private/private.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mechanicat Bot | {% block title %}Home{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'Adminator-admin-dashboard/build/style.css' %}">
</head>
<body class="app">
    <div>
        <div class="sidebar">
            <div class="sidebar-inner">
                {% include 'base/private/sidebar-logo.html' %}
                {% include 'base/private/sidebar-menu.html' %}
            </div>
        </div>
        <div class="page-container">
            {% include 'base/general/alerts.html' %}
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
    <script src="{% static 'Adminator-admin-dashboard/build/vendor.js' %}"></script>
    <script src="{% static 'Adminator-admin-dashboard/build/bundle.js' %}"></script>
</html>

templates/base/private/sidebar-logo.html
{% load static %}
<div class="sidebar-logo">
    <div class="peers ai-c fxw-nw">
        <div class="peer peer-greed">
            <a href="{% url 'pages:dashboard' %}" class="sidebar-link td-n">
                <div class="peers ai-c fxw-nw">
                    <div class="peer">
                        <div class="logo">
                            <img src="{% static 'Adminator-admin-dashboard/build/assets/static/images/logo.png' %}" alt="">
                        </div>
                    </div>
                    <div class="peer peer-greed">
                        <h5 class="lh-1 mB-0 logo-text">Mechanicat</h5>
                    </div>
                </div>
            </a>
        </div>
        <div class="peer">
            <div class="mobile-toggle sidebar-toggle">
                <a href="#" class="td-n">
                    <i class="ti-arrow-circle-left"></i>
                </a>
            </div>
        </div>
    </div>
</div>

templates/base/private/sidebar-menu.html
<ul class="sidebar-menu scrollable pos-r ps">

</ul>

templates/base/public.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mechanicat Bot | {% block title %}Home{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'shards-ui/dist/css/shards.min.css' %}">
</head>
<body>
    {% include 'base/public_navbar.html' %}
    {% include 'base/alerts.html' %}
    {% block content %}{% endblock %}
</body>
<script src="{% static 'jquery/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'shards-ui/dist/js/shards.min.js' %}"></script>
</html>

templates/base/public_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
  <a class="navbar-brand" href="{% url 'pages:home' %}">Mechanicat Bot</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown-1" aria-controls="navbarNavDropdown-1"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown-1">
    <ul class="navbar-nav ml-auto">
        {% if not request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:signup' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:login' %}">Login</a>
          </li>
        {% else %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              {{ request.user.first_name }} {{ request.user.last_name }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Go to Dashboard</a>
              <a class="dropdown-item" href="#">My Bots</a>
              <a class="dropdown-item" href="#">View Profile</a>
            </div>
          </li>
          <li>
              <a class="nav-link" href="{% url 'pages:logout' %}">Logout</a>
          </li>
        {% endif %}
    </ul>
  </div>
</nav>

templates/pages/auth_form.html
{% extends 'base/public/public.html' %}

{% block title %} Login {% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="mb-4">{{ action }}</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <form action="." method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            {% if request.GET.next %}
                                <input type="hidden" name="next" value="{{ request.GET.next }}">
                            {% endif %}
                            <input type="submit" class="btn btn-primary" value="{{ action }}">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/dashboard.html
{% extends 'base/private/private.html' %}

{% block title %}Dashboard{% endblock %}

templates/pages/home.html
{% extends 'base/public/public.html' %}

{% block content %}
    <h1>Home</h1>
{% endblock %}

templates/pages/login.html
{% extends 'base/public.html' %}

{% block title %} Login {% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="mb-4">Login</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <form action="." method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" class="btn btn-primary" value="Login">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}